apiVersion: apps/v1
kind: Deployment
metadata:
  name: incert
spec:
  replicas: 1
  selector:
    matchLabels:
      app: incert
  template:
    metadata:
      labels:
        app: incert
    spec:
      containers:
      - image: okteto.dev/incert:latest
        name: incert
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "271c7384-4e4e-4c0a-b11a-62a2fa2c0142"
        - name: Vless_Path
          value: "/vl334466"
        - name: Vmess_UUID
          value: "271c7384-4e4e-4c0a-b11a-62a2fa2c0142"
        - name: Vmess_Path
          value: "/vm778899"
        - name: Share_Path
          value: "/v2link"
