apiVersion: apps/v1
kind: Deployment
metadata:
  name: onelve
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onelve
  template:
    metadata:
      labels:
        app: onelve
    spec:
      containers:
      - image: okteto.dev/onelve:latest
        name: onelve
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "bffa4b6f-e638-4491-9aba-acb50e9a5cd1"
        - name: Vless_Path
          value: "/vl3666"
        - name: Vmess_UUID
          value: "bffa4b6f-e638-4491-9aba-acb50e9a5cd1"
        - name: Vmess_Path
          value: "/vm778866"
        - name: Share_Path
          value: "/v2link"
